### ISSUE TITLE
__fisher_complete no longer exists

### ISSUE THREAD

**Issue by jethrokuan** [fisherman/vault#1]
Now that fisherman is at 2.0.0, `__fisher_complete` is removed. I haven't taken a look at the new code yet, so I'm not quite sure what to replace it with.

**Comment by bucaran** [comment]
With nothing. One must write their own completions now. I know what you'll say, "but `__fisher_complete` was nice". Yes, it was, but it was also a dependency. It's not a big deal.

**Comment by jethrokuan** [comment]
@bucaran Not sure why the issue is closed, because it's not fixed yet. Installing vault will throw errors.
